name: bagel
channels:
  - nvidia
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - asttokens=3.0.1=pyhd8ed1ab_0
  - binutils_impl_linux-64=2.44=h4b9a079_2
  - binutils_linux-64=2.44=hc03a8fd_2
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - certifi=2026.1.4=pyhd8ed1ab_0
  - comm=0.2.3=pyhe01879c_0
  - cuda-cccl_linux-64=12.8.90=0
  - cuda-command-line-tools=12.8.1=0
  - cuda-compiler=12.8.1=0
  - cuda-crt-dev_linux-64=12.8.93=h06a4308_3
  - cuda-crt-tools=12.8.93=h06a4308_3
  - cuda-cudart=12.8.90=0
  - cuda-cudart-dev=12.8.90=0
  - cuda-cudart-dev_linux-64=12.8.90=0
  - cuda-cudart-static=12.8.90=0
  - cuda-cudart-static_linux-64=12.8.90=0
  - cuda-cudart_linux-64=12.8.90=0
  - cuda-cuobjdump=12.8.90=0
  - cuda-cupti=12.8.90=0
  - cuda-cupti-dev=12.8.90=0
  - cuda-cuxxfilt=12.8.90=0
  - cuda-driver-dev=12.8.90=0
  - cuda-driver-dev_linux-64=12.8.90=0
  - cuda-gdb=12.8.90=0
  - cuda-libraries=12.8.1=0
  - cuda-libraries-dev=12.8.1=0
  - cuda-nsight=12.8.90=0
  - cuda-nvcc=12.8.93=0
  - cuda-nvcc-dev_linux-64=12.8.93=he2511ca_3
  - cuda-nvcc-impl=12.8.93=hd1a145a_3
  - cuda-nvcc-tools=12.8.93=hbdd6827_3
  - cuda-nvcc_linux-64=12.8.93=0
  - cuda-nvdisasm=12.8.90=0
  - cuda-nvml-dev=12.8.90=0
  - cuda-nvprof=12.8.90=0
  - cuda-nvprune=12.8.90=0
  - cuda-nvrtc=12.8.93=0
  - cuda-nvrtc-dev=12.8.93=0
  - cuda-nvtx=12.8.90=0
  - cuda-nvvm-dev_linux-64=12.8.93=h06a4308_3
  - cuda-nvvm-impl=12.8.93=hbdd6827_3
  - cuda-nvvm-tools=12.8.93=hbdd6827_3
  - cuda-nvvp=12.8.93=0
  - cuda-opencl=12.8.90=0
  - cuda-opencl-dev=12.8.90=0
  - cuda-profiler-api=12.8.90=0
  - cuda-sanitizer-api=12.8.93=0
  - cuda-toolkit=12.8.1=0
  - cuda-tools=12.8.1=0
  - cuda-version=12.8=3
  - cuda-visual-tools=12.8.1=0
  - dbus=1.16.2=h5bd4931_0
  - debugpy=1.8.19=py310h8a20257_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - expat=2.7.3=h7354ed3_4
  - fontconfig=2.15.0=h2c49b7f_0
  - freetype=2.13.3=h4a9f257_0
  - gcc_impl_linux-64=14.3.0=h4943218_4
  - gcc_linux-64=14.3.0=hda73cce_12
  - gds-tools=1.13.1.3=0
  - gmp=6.3.0=h6a678d5_0
  - gxx_impl_linux-64=14.3.0=he634eba_4
  - gxx_linux-64=14.3.0=hca8765c_12
  - icu=73.1=h6a678d5_0
  - ipykernel=7.1.0=pyha191276_0
  - ipython=8.37.0=pyh8f84b5b_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jupyter_client=8.7.0=pyhcf101f3_0
  - jupyter_core=5.9.1=pyhc90fa1f_0
  - kernel-headers_linux-64=4.18.0=h3108a97_1
  - keyutils=1.6.3=hb9d3cd8_0
  - krb5=1.21.3=h659f571_0
  - ld_impl_linux-64=2.44=h153f514_2
  - libcublas=12.8.4.1=0
  - libcublas-dev=12.8.4.1=0
  - libcufft=11.3.3.83=0
  - libcufft-dev=11.3.3.83=0
  - libcufile=1.13.1.3=0
  - libcufile-dev=1.13.1.3=0
  - libcurand=10.3.9.90=0
  - libcurand-dev=10.3.9.90=0
  - libcusolver=11.7.3.90=0
  - libcusolver-dev=11.7.3.90=0
  - libcusparse=12.5.8.93=0
  - libcusparse-dev=12.5.8.93=0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libexpat=2.7.3=h7354ed3_4
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h69a1729_7
  - libgcc-devel_linux-64=14.3.0=he7458c1_104
  - libgcc-ng=15.2.0=h166f726_7
  - libglib=2.84.4=h77a78f3_0
  - libgomp=15.2.0=h4751f2c_7
  - libiconv=1.16=h5eee18b_3
  - libnpp=12.3.3.100=0
  - libnpp-dev=12.3.3.100=0
  - libnsl=2.0.0=h5eee18b_0
  - libnvfatbin=12.8.90=0
  - libnvfatbin-dev=12.8.90=0
  - libnvjitlink=12.8.93=1
  - libnvjitlink-dev=12.8.93=1
  - libnvjpeg=12.3.5.92=0
  - libnvjpeg-dev=12.3.5.92=0
  - libpng=1.6.50=h2ed474d_0
  - libsanitizer=14.3.0=hd4faa28_4
  - libsodium=1.0.20=h4ab18f5_0
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-devel_linux-64=14.3.0=he7458c1_104
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libxkbcommon=1.9.1=h69220b7_0
  - libxml2=2.13.9=h2c43086_0
  - libzlib=1.3.1=hb25bd0a_0
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - ncurses=6.5=h7934f7d_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - nsight-compute=2025.1.1.2=0
  - nspr=4.37=h8459abe_0
  - nss=3.117=h3135ca0_0
  - ocl-icd=2.3.3=h47b2149_0
  - opencl-headers=2025.07.22=hfb20e49_0
  - openssl=3.6.0=h26f9b46_0
  - parso=0.8.5=pyhcf101f3_0
  - pcre2=10.46=hf426167_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pip=25.3=pyhc872135_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - pthread-stubs=0.3=h0ce48e5_1
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - python=3.10.19=h6fa692b_0
  - python_abi=3.10=2_cp310
  - pyzmq=27.1.0=py310h4f33d48_0
  - readline=8.3=hc2a1206_0
  - setuptools=80.9.0=py310h06a4308_0
  - sqlite=3.51.0=h2a70700_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - sysroot_linux-64=2.28=h3108a97_1
  - tk=8.6.15=h54e0aa7_0
  - tornado=6.5.4=py310ha78b2d2_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.15.0=pyhcf101f3_0
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - wheel=0.45.1=py310h06a4308_0
  - xkeyboard-config=2.44=h382ed1a_1
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zeromq=4.3.5=h387f397_9
  - zlib=1.3.1=hb25bd0a_0
  - pip:
      - accelerate==1.12.0
      - aiofiles==24.1.0
      - annotated-doc==0.0.4
      - annotated-types==0.7.0
      - anyio==4.12.0
      - bitsandbytes==0.49.0
      - brotli==1.2.0
      - charset-normalizer==3.4.4
      - click==8.3.1
      - contourpy==1.3.2
      - cycler==0.12.1
      - decord==0.6.0
      - einops==0.8.1
      - exceptiongroup==1.3.1
      - fastapi==0.128.0
      - ffmpy==1.0.0
      - filelock==3.20.1
      - flash-attn==2.5.8
      - fonttools==4.61.1
      - fsspec==2025.12.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - gradio==5.38.2
      - gradio-client==1.11.0
      - groovy==0.1.2
      - h11==0.16.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.29.1
      - idna==3.11
      - jinja2==3.1.6
      - kiwisolver==1.4.9
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - matplotlib==3.7.0
      - mdurl==0.1.2
      - mpmath==1.3.0
      - networkx==3.4.2
      - ninja==1.13.0
      - numpy==1.24.4
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - opencv-python==4.7.0.72
      - orjson==3.11.5
      - packaging==25.0
      - pandas==2.3.3
      - pillow==11.3.0
      - platformdirs==4.5.1
      - protobuf==6.33.2
      - psutil==7.2.0
      - pyarrow==11.0.0
      - pydantic==2.11.10
      - pydantic-core==2.33.2
      - pydub==0.25.1
      - pygments==2.19.2
      - pyparsing==3.3.1
      - python-dateutil==2.9.0.post0
      - python-multipart==0.0.21
      - pytz==2025.2
      - pyyaml==6.0.2
      - regex==2025.11.3
      - requests==2.32.3
      - rich==14.2.0
      - ruff==0.14.10
      - safehttpx==0.1.7
      - safetensors==0.4.5
      - scipy==1.10.1
      - semantic-version==2.10.0
      - sentencepiece==0.1.99
      - sentry-sdk==2.48.0
      - shellingham==1.5.4
      - six==1.17.0
      - smmap==5.0.2
      - starlette==0.50.0
      - sympy==1.13.1
      - tokenizers==0.21.4
      - tomlkit==0.13.3
      - torch==2.5.1
      - torchvision==0.20.1
      - tqdm==4.67.1
      - transformers==4.49.0
      - triton==3.1.0
      - typer==0.21.0
      - typing-inspection==0.4.2
      - tzdata==2025.3
      - urllib3==2.6.2
      - uvicorn==0.40.0
      - wandb==0.23.1
      - websockets==15.0.1
      - xlsxwriter==3.2.9
prefix: /data01/yjf/miniconda3/envs/bagel2
